import Head from 'next/head'
import Header from '../components/Header'
import About from '../components/About'
import Portfolio from '../components/Portfolio'
import Article from '../components/Article'
import Skills from '../components/Skills'
import Why from '../components/Why'
import Form from '../components/Form'
import Footer from '../components/Footer'

export default function Home({post}) {
  return (
    <div className="Home">
      <Head>
        <title>Guillaume David | Développeur Front End Freelance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="gd.ico"/>
      </Head>

      <Header />
      <About />
      <Portfolio />
      <Article posts={post}/>
      <Skills />
      <Why />
      <Form />
      <Footer />



    </div>
  )
}


export async function getStaticProps ({params}) {
    const post = await fetch(`https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@guillaumedaavid`).then(r => r.json())
    return {
      props: {
        post
      }
    }
}