import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className="Home">
      <Head>
        <title>Guillaume David | Développeur Front End Freelance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />



    </div>
  )
}
